<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function module_path_list_form_system_modules_alter(&$form, &$form_state, $form_id) {

  // Do not alter the form in a confirmation page.
  if (isset($form['confirm'])) {
    return;
  }

  $groups = element_children($form['modules']);
  foreach ($groups as $group_key => $group_name) {
    $modules_group = element_children($form['modules'][$group_name]);
    foreach ($modules_group as $module_key => $module_name) {
      $path = drupal_get_path('module', $module_name);
      if ($path) {
        if (!empty($form['modules'][$group_name][$module_name]['description'])
            && !empty($form['modules'][$group_name][$module_name]['description']['#markup'])) {

          // Already has a description, append a line break to it.
          $form['modules'][$group_name][$module_name]['description']['#markup'] .= '<br/>';
        }
        else {

          // Description is not set or is empty.
          $form['modules'][$group_name][$module_name]['description']['#markup'] = '';
        }

        // Concatenate module's path.
        $form['modules'][$group_name][$module_name]['description']['#markup'] .= t('Path') . ': <b>' . $path . '</b>';
      }
    }
  }
}
