<?php

/**
 * Implements hook_form_alter().
 */
function min_price_order_form_views_form_commerce_cart_form_default_alter(&$form, &$form_state) {
  $form['output']['#markup'] = "<div class='basket1 cart'>".$form['output']['#markup'].'</div>';
  $form['actions']['submit']['#value'] = 'Пересчитать';
  $form['actions']['checkout']['#value'] = 'Оформить';
  $order = commerce_order_load($form_state['order']->order_id);
  $total_price = $order->commerce_order_total['und'][0]['amount']/100;
  if($total_price < 3000){
    drupal_set_message(('<span style="color:red;">По правилам нашего магазина минимальная сумма заказа составляет 3000 рублей.</span>'), $type = 'warning', FALSE);
    drupal_add_css('#edit-checkout {display: none}', 'inline');
    $form['output']['#markup'] .= <<<HTML
        <script>
       (function ($) {
          $(document).ready(function() {
              $("input#edit-submit").replaceWith("<button type='submit' class='button_flex bf2' onclick='window.history.back();return false;'><span><span>Вернуться к покупкам</span></span></button> <button type='submit' name='op' value='Пересчитать' class='button_flex bf2 refresh'><span><span>Пересчитать</span></span></button> ");
          });
        }(jQuery));
        </script>
HTML;
  }  else {
    $form['output']['#markup'] .= <<<HTML
        <script>
       (function ($) {
          $(document).ready(function() {
              $("input#edit-submit").replaceWith("<button type='submit' class='button_flex bf2' onclick='window.history.back();return false;'><span><span>Вернуться к покупкам</span></span></button> <button type='submit' name='op' value='Пересчитать' class='button_flex bf2 refresh'><span><span>Пересчитать</span></span></button> ");
              $("input#edit-checkout").replaceWith("<button type='submit' name='op' class='button_flex checkout' value='Оформить'><span><span>Оформить заказ</span></span></button>");
          });
        }(jQuery));
        </script>
HTML;
  }
}