<?php

/**
 * Implement hook_js_alter()
 * @param $js
 */

function jquery_migrate_js_alter(&$javascript) {
  $javascript['misc/jquery-1.10.2.min.js']['weight'] = 0;
  $javascript['misc/jquery-1.10.2.min.js']['group'] = -101;
  $migrate_file = $GLOBALS['base_root'] . '/misc/jquery-migrate-1.2.1.min.js';
  $migrate_version = '1.2.1';
  drupal_add_js($migrate_file);
  if (isset($javascript["$migrate_file"])) {
    $javascript["$migrate_file"]['version'] = $migrate_version;
    $javascript["$migrate_file"]['weight'] = 1;
    $javascript["$migrate_file"]['group'] = -101;
  }
  $javascript['settings']['scope'] = 'footer';
    unset($javascript['modules/user/user.js']);
}